### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by ACsillaghy** [explore-platform/s-disco#1]
It remains in the "starting" position forever (2 days now) 

<img width="1045" alt="Screenshot 2024-05-21 at 06 51 19" src="https://github.com/explore-platform/s-disco/assets/18006843/82105c8b-d1d4-41df-89b8-f858235d7886">

**Comment by kalaschsoyuz** [comment]
The instance did not start properly due to an internal time-out (data load took too long). A 'loading screen' has been added to prevent this time-out. The instance on explore-platform.eu has been updated.
